### ISSUE TITLE
linux portable linux download link not working

### ISSUE THREAD

**Issue by bingoxo** [mbruel/ngPost#3] opened 2019-12-04 09:45 UTC
did you remove it ?

**Comment by mbruel** [comment] 2019-12-04 20:58
Hi,
I've updated the link to the previous release (v1.1) and added an AppImage for the new release.
I didn't try on many architectures, please let me know if you have issues with it.
Cheers

**Comment by bingoxo** [comment] 2019-12-04 21:47
i'm trying to restore my .conf file , i put it in /home/user/.ngPost but it doesn't get picked up with the app

**Comment by mbruel** [comment] 2019-12-04 23:37
hum... not sure, it is working fine on my environment.
what is your distribution?
The default config file should be $HOME/.ngPost
When it is picked up, if you launch it from a terminal you should see this message:
$ ./ngPost_v1.2-x86_64.AppImage 
Using default config file:  "/home/bruel/.ngPost"

But there are no message in case it doesn't exist...
Check if you've the HOME environment variable defined but it should... (echo $HOME)
try:
gedit $HOME/.ngPost
and paste the config file https://raw.githubusercontent.com/mbruel/ngPost/master/ngPost.conf

**Comment by bingoxo** [comment] 2019-12-05 00:02
i was talking about the gui , the cli can see  the config

**Comment by bingoxo** [comment] 2019-12-05 00:42
now i keep getting error 441 posting failed

**Comment by mbruel** [comment] 2019-12-05 09:52
well how often?
Can you tell me how many Articles you are uploading (that's the number on the right of the progress bar, before the avg. speed) and how many gets the 441 answer.

it could be because the ID is already in use... but normally it should be more explicit...
well I'm ignoring failed Article and going to next one as I thought this should never happen...
I'm going to add on the next version a retry loop for the Articles and only display the error when the posting failed 5 times...

I may also allow to activate a debug mode...

**Comment by bingoxo** [comment] 2019-12-05 10:37
19000 articles , most of them get uploaded and with some i get that error

**Comment by mbruel** [comment] 2019-12-05 10:42
ok then I'll definitely add the robustness for the next version that I'll try to release by the end of the week.
I suppose you use redundancy with par2 files? Are you able to download your post even with those few articles missing?

**Comment by bingoxo** [comment] 2019-12-05 11:06
it failes even with pars

**Comment by mbruel** [comment] 2019-12-05 11:09
hum... then you must have quite a lot of failed Articles...
I gonna work on the robustness straight away, I'll let you know when the next release is ready ;)

**Comment by bingoxo** [comment] 2019-12-05 11:14
Merci ^^ / Thanks

**Comment by mbruel** [comment] 2019-12-05 17:38
de rien héhé!
the new release is available, please give it a try and let me know if you still have Failed Article.
I couldn't really test it as I never get this issue but normally if it happens we will try to post it again with another msg-id. We do 5 retries by default but you can configure that number.
There are few other improvement, especially the possibility to stop an ongoing post.
cf the release note:

####################################################
###       Release: ngPost v1.3                   ###
###       date:    2019/12/05                    ###
####################################################

- add robustness on posting articles by retrying a number of times if Failure

- new option -r or -retry for that purpose (default value 5)

- allow to stop an ongoing post from the HMI

- add some tooltips for the options (HMI)

- fix potential crash (double deletion of NgPost::_file)

**Comment by mbruel** [comment] 2019-12-05 17:39
PS: please close this issue if you don't get this issue anymore ;)

**Comment by bingoxo** [comment] 2019-12-05 19:38
https://i.imgur.com/SYWgmTu.jpg

it either crashes or is stuck at 98% like in picture and many times the speed is miscalculated (see picture)


t'es sur irc ou discord ?

**Comment by mbruel** [comment] 2019-12-06 00:22
I see...
no I don't have discord but I could create an account or we could meet on a private chan on irc.
I don't manage to reproduce your situation, I never get failed articles... not sure the reason you have some...
From what i see on your pic, I would assume that testxx.part12.rar should be green instead of black. I've tried to code that even if you don't manage to post an article, you try few more times and if you don't succeed, it should act as if it has... you'll just have a sum up at the end telling you the number of articles that havn't been updated...
I could send you a debug version, maybe it will help to debug... 
Otherwise send me a mail, we could chat on gmail?

**Comment by bingoxo** [comment] 2019-12-06 00:30
i'm using ubuntu 18.10 , tried 16.04 before as well , trying with gui , and haven't had a succecful upload yet , i would suggest chatting over app.wire.com , asks only for email , i sent you an email 2 days ago , that's why i'm asking for a better way of communication , si c'est possible bien sur

**Comment by mbruel** [comment] 2019-12-06 00:42
are you geeko?
french?
well for me email is easier, we could get on anything else where we can talk after if needed.

**Comment by bingoxo** [comment] 2019-12-06 00:59
oui c'est geeko

**Comment by bingoxo** [comment] 2019-12-12 11:44
i tried in another server and it's working fine , so it's probably problem with the first one not ngpost , the only issue i still encounter is the misrepresented speed

**Comment by mbruel** [comment] 2019-12-12 11:53
Hello,
Well even if there is a problem on your first server, ngPost shouldn't freeze or crash... I'd really like to be able to debug it... Hum I guess I gonna have to write some code to simulate a usenet server :\
For the speed thing, can you tell me more. In what circumstances you noticed it? Only when there are articles refused?
By choice, the avg speed is not the actual upload speed but the speed of acceptance of Articles.
What I mean is that if the server refuse an Article, then we don't count the data sent for that failure. Does it make sense?

**Comment by mbruel** [comment] 2019-12-12 11:55
PS: would be better if you could close this issue (as I'm releasing now the Linux portable AppImage) and create another one with a relevant title and information. (for the avg. speed problem and/or for the crash)
Cheers

**Closed** 2019-12-12 14:28 UTC
