### ISSUE TITLE
[Bug] QCoreApplication::postEvent: Unexpected null receiver

### ISSUE THREAD

**Issue by AssRap3r** [mbruel/ngPost#23] opened 2020-02-26 09:00 UTC
I get this message at the end of posting, it looks to be repeated for the same amount of connections you have for posting (ie: 40 connections = message repeated 40 times)

using 4.4

```
Upload size: 4.63 GB in 00:01:05.718 (65 sec) => average speed:  72.10 MB/s (40 connections on 8 threads)
nzb file: /home/sneed/mysecretupload.nzb


QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
[==================================================] 100 % (7005 / 7005) avg. speed:  72.08 MB/s
 => closing application
ngPost closed propertly!
```

It doesn't appear to cause any problems with the resulting nzb file. the command I'm using is ngPost -o "$base.nzb" -i "$prefix $dir", base, prefix & dir are set in a separate script

**Comment by mbruel** [comment] 2020-03-07 16:43
hum this is quite hard to track...
Do you have it every time or randomly?
I've submitted a potential fix but I'm not sure it will be that. Could be...
Can you compile yourself or do you need me to provide a binary?
```
commit 2805a22b821adf23d7246c4a20d0bbb1a197a20b (HEAD -> master, origin/master, origin/HEAD)
Author: Matthieu Bruel <Matthieu.Bruel@gmail.com>
Date:   Sat Mar 7 17:39:49 2020 +0100

    issue #23. don't postpone deletion of the socket of the NntpConnection
```

**Comment by AssRap3r** [comment] 2020-03-08 17:52
> Do you have it every time or randomly?

happens every time. compiled myself on Ubuntu 18.04 box, after posting error:

```
malloc_consolidate(): invalid chunk size
Aborted (core dumped)
```
the nzb appears to be fine though.

**Comment by mbruel** [comment] 2020-03-10 21:45
is my fix doing anything better? or not at all?

**Comment by mbruel** [comment] 2020-03-11 15:03
I've made a better fix. 
The crash introduced by the previous change is removed. Normally ngPost is now closing properly and the GUI is not crashing anymore at the end of a post.
Hopefully your bug should have disappear too.
Please confirm.
I've tried several time, I can't reproduce it on my environments. I use also 8 threads and 40 connections...
Which version of Qt do you use?
Can you try if you have it also with the AppImage that is built with Qt v5.12.6
Cheers ;)

**Comment by AssRap3r** [comment] 2020-03-11 23:19
> Which version of Qt do you use?
```
QMake version 3.1
Using Qt version 5.9.5 in /usr/lib/x86_64-linux-gnu
```

> Can you try if you have it also with the AppImage that is built with Qt v5.12.6

Same error with 4.4 v5.12.6 - null receiver

latest github:

```
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState
[==================================================] 100 % (147 / 147) avg. speed:  39.89 MB/s
 => closing application
ngPost closed properly!
```

**Comment by mbruel** [comment] 2020-03-12 00:57
hum ok... seems to be a warning that should be removed by Qt (cf [that bug](https://bugreports.qt.io/browse/QTBUG-50711))
can you try the latest commit plz

**Comment by AssRap3r** [comment] 2020-03-12 09:29
No change, still gives the same error:

`QAbstractSocket::waitForDisconnected() is not allowed in UnconnectedState`

**Comment by mbruel** [comment] 2020-03-12 09:45
what about now? otherwise I don't think I can remove it... it seems it has been removed by Qt on v5.14....

**Comment by AssRap3r** [comment] 2020-03-12 12:23
All good now

```
Start posting: test.nzb
Number of available Nntp Connections: 10
[=============>                                    ] 26 % (39 / 147) avg. speed:
[=============================>                    ] 58 % (86 / 147) avg. speed:
[==========================================>       ] 84 % (124 / 147) avg. speed:  43.05 MB/s
Upload size: 100.00 MB in 00:00:02.182 (2 sec) => average speed:  45.83 MB/s (10 connections on 8 threads)
nzb file: /home/sneed/test_2.nzb


[==================================================] 100 % (147 / 147) avg. speed:  45.72 MB/s
 => closing application
ngPost closed properly!
```

**Comment by mbruel** [comment] 2020-03-12 12:52
great! 
I'm closing the issue then

**Closed by mbruel** 2020-03-12 12:52 UTC
