### ISSUE TITLE
[Request] Progress bar for Rar and PAR

### ISSUE THREAD

**Issue by kDipak** [mbruel/ngPost#29] opened 2020-03-19 10:47 UTC
Hello There,

the rar and par function currently shows the command line but no further output in the default state (unlike in -d, but that shows a lot of info, the rar info looks reasonable but the par shows 10 lines per %) 

is it possible to add a progression bar or some indicator of how far it is with the rar or par operation ?

**Comment by mbruel** [comment] 2020-03-19 11:17
I can't predict which software will be used either for compression or for par2 generation: rar or 7zip ; par2cmdline, Parpar, Multipar
So it's quite tricky to parse the output of those external process to get the progression...

Rar and 7z logs are ok.
par2cmdline are too much but it is strongly advised to use Parpar instead. I'll probably integrate it in the next release. For now you can [download it here](https://github.com/animetosho/ParPar/releases/download/v0.3.1/parpar.v0.3.1.win64.7z).
Then Edit the config file to set:
```
PAR2_PATH = /your_full_path/parpar.exe

PAR2_ARGS = -s5M -r8% -m2048M --progress stdout -q
```
the problem is that then the percentage of redundancy will be fixed, par2_pct will be ignored.
If that's an issue for, you could use:
` -s5M -r1n*0.6 -m2048M -p1l  --progress stdout -q`

I let you check the parpar.exe --help to understand all the parameters but for a nice output, definitely put the` --progress stdout -q`

You'll see, Parpar is at least 3 times faster to generate the par2 ;)
Cheers!

**Comment by kDipak** [comment] 2020-03-19 13:38
thank i will try out the parpar.

**Closed** 2020-03-19 16:25 UTC

**Comment by mbruel** [comment] 2020-03-19 16:54
cool.
I've pushed a new fix to allow to have 2 modes of debug information:
```
Syntax: ngPost (options)* (-i <file or folder> | --auto <folder> | --monitor <folder>)+
	--help             : Help: display syntax
	-v or --version    : app version
	-c or --conf       : use configuration file (if not provided, we try to load $HOME/.ngPost)
	--disp_progress    : display cmd progressbar: NONE (default), BAR or FILES
	-d or --debug      : display extra information
	--fulldebug        : display full debug information
	-l or --lang       : application language
```
So basically if the normal -d, you'll get the output of the rar and par2 external processes plus few limited more logs but not all the one you got now.
Those will be reserved for the keyword --fulldebug in case there is a crash and I need information to debug on my side.
Here is a version for you to try :)
